### ISSUE TITLE
Error messages from 1.2.3

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#1109]
Got the following errors when running automl.fit() with flaml 1.2.3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/flaml/automl/automl.py", line 1677, in fit
    task.validate_data(
  File "/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/flaml/automl/task/generic_task.py", line 201, in validate_data
    ) = automl._transformer.fit_transform(X, y, self)
  File "/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/flaml/automl/data.py", line 360, in fit_transform
    from sklearn.impute import SimpleImputer
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/sklearn/impute/__init__.py", line 4, in <module>
    from ._base import MissingIndicator, SimpleImputer
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/sklearn/impute/_base.py", line 13, in <module>
    from ..base import BaseEstimator, TransformerMixin, _fit_context
ImportError: cannot import name '_fit_context' from 'sklearn.base' (/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/sklearn/base.py)

@sonichi  Please advise. Thank you.

**Comment by sonichi** [comment]
The import fails for sklearn. You may want to check the sklearn version in
/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/sklearn
The version needs to be scikit-learn>=0.24

**Comment by flippercy** [comment]
scikit-learn in /home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (1.3.0)

**Comment by flippercy** [comment]
Fixed. Thank you for the help!
