### ISSUE TITLE
struct error during ensemble

### ISSUE THREAD

**Issue by stepthom** [microsoft/FLAML#134]
When FLAML is building the ensemble at the end of a run, I am seeing the following error message:

```
[flaml.automl: 07-10 06:16:01] {1153} INFO -  at 9912.2s,       best xgboost's error=0.1893,    best xgboost's error=0.1893
[flaml.automl: 07-10 06:16:01] {1001} INFO - iteration 183, current learner lgbm
[flaml.automl: 07-10 06:17:00] {1153} INFO -  at 9970.5s,       best lgbm's error=0.1928,       best xgboost's error=0.1893
[flaml.automl: 07-10 06:17:00] {1193} INFO - selected model: XGBClassifier(base_score=0.5, booster='gbtree',
              colsample_bylevel=0.6553649023281938, colsample_bynode=1,
              colsample_bytree=0.5733906723952086, gamma=0, gpu_id=-1,
              grow_policy='lossguide', importance_type='gain',
              interaction_constraints='', learning_rate=0.03981439313350194,
              max_delta_step=0, max_depth=0, max_leaves=1130,
              min_child_weight=5.542464309441731, missing=nan,
              monotone_constraints='()', n_estimators=123, n_jobs=10,
              num_parallel_tree=1, objective='multi:softprob', random_state=0,
              reg_alpha=0.0059793400625186045, reg_lambda=7.330769622156848,
              scale_pos_weight=None, subsample=1.0, tree_method='hist',
              use_label_encoder=False, validate_parameters=1, verbosity=0)[flaml.automl: 07-10 06:17:00] {1203} INFO - [('xgboost', <flaml.model.XGBoostSklearnEstimator object at 0x7f3e68c55048>), ('lgbm', <flaml.model.LGBMEstimator object at 0x7f3ea4da8cc0>), ('rf', <flaml.model.RandomForestEstimator object at 0x7f3ef11bc278>), ('extra_tree', <flaml.model.ExtraTreeEstimator object at0x7f3ea4fb9240>), ('catboost', <flaml.model.CatBoostEstimator object at 0x7f3ef24f5c50>)]
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/global/home/hpc3552/autotext/flaml_env/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 357, in _sendback_result
    exception=exception))
  File "/global/home/hpc3552/autotext/flaml_env/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 247, in put
    self._writer.send_bytes(obj)
  File "/opt/python/anaconda3/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/python/anaconda3/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "search.py", line 230, in <module>
    main()
  File "search.py", line 226, in main
    data_sheet = run_data_sheet(data_sheet, target_col, id_col, data_dir, out_dir, eval_metric)
  File "search.py", line 181, in run_data_sheet
    pipe.fit(X_train, y_train, **automl_settings)
  File "/global/home/hpc3552/autotext/flaml_env/lib/python3.6/site-packages/flaml/automl.py", line 950, in fit
    self._search()
  File "/global/home/hpc3552/autotext/flaml_env/lib/python3.6/site-packages/flaml/automl.py", line 1222, in _search
    **self._state.fit_kwargs)
  File "/global/home/hpc3552/autotext/flaml_env/lib/python3.6/site-packages/sklearn/ensemble/_stacking.py", line 441, in fit
    return super().fit(X, self._le.transform(y), sample_weight)
  File "/global/home/hpc3552/autotext/flaml_env/lib/python3.6/site-packages/sklearn/ensemble/_stacking.py", line 149, in fit
    for est in all_estimators if est != 'drop'
  File "/global/home/hpc3552/autotext/flaml_env/lib/python3.6/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/global/home/hpc3552/autotext/flaml_env/lib/python3.6/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/global/home/hpc3552/autotext/flaml_env/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/opt/python/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/python/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

Interestingly, this error does not occur every time, but only sometimes.

**Comment by stepthom** [comment]
After doing some reading online (https://github.com/scikit-learn/scikit-learn/issues/3313 and https://stackoverflow.com/questions/24406937/scikit-learn-joblib-bug-multiprocessing-pool-self-value-out-of-range-for-i-fo), this seems to be related to memory usage.

The weird part is, I have run FLAML many times on this same dataset on this same machine, without experience the error. But it only occurs sometimes.

I am going to experiment with fewer `n_jobs` as a workaround. (One guess I have is that if I set `n_jobs` to, say, 10, then all the individual estimators will use 10 jobs, plus the stacker, resulting it many, many copies of the dataset while building the stacking classifier. )

**Comment by stepthom** [comment]
FWIW, I am using 64-bit version of Python:

```
$ python --version
Python 3.6.8 :: Anaconda custom (64-bit)
```

**Comment by stepthom** [comment]
Update: This error does not occur if I use a machine with more memory. So it is definitely memory-usage related and I don't believe this is an issue with FLAML in particular. It is possible that FLAML and/or scikit learn has a subtle memory leak somewhere that triggers this error, but it is also possible that this is a ulimit/OS type limitation.

This is no longer a blocker for me so I will close.
