### ISSUE TITLE
problems setting up a custom metric

### ISSUE THREAD

**Issue by itabhiyanta** [microsoft/FLAML#222]
HI I am trying to setup a  custom metric but I keep getting an error about the custom metric having more arguments than what it should have
`TypeError: custom_metric() takes 5 positional arguments but 11 were given`

My code looks like this

```
automl = AutoML()
dataset_handler # initialize dataset_handler here
def custom_metric(X_test, y_test, estimator, X_train, y_train):
        outputs = estimator.predict(X_test)
        y_true = np.asarray(dataset_handler.test_set_output[
                                dataset_handler.cfg.label_column_name].tolist())
        y_pred = np.asarray(outputs)
        mape_error = round(
            np.mean(np.abs((y_true - y_pred) / y_true)) * 100, 3)
        print('Mape error (manually calculated is :', str(mape_error), file=log_file)
        return mape_error, estimator.get_params

settings = {
        "time_budget": 3600,  # total running time in seconds
        "metric": custom_metric,  # primary metrics for regression can be chosen from: ['mae','mse','r2']
        "estimator_list": ['lgbm', 'xgboost'],  # list of ML learners; we tune lightgbm in this example
        "task": 'regression',  # task type
        "log_file_name": 'exp2_flaml_custom_lgb_xgb.log',  # flaml log file
        "seed": 7654321,  # random seed
    }
automl.fit(X_train=dataset_handler.x_train.to_numpy(), y_train=dataset_handler.y_train.to_numpy(),
               X_val=dataset_handler.x_test.to_numpy(), y_val=dataset_handler.test_set_output.to_numpy(), **settings)
```

I am wondering what am I doing wrong. Can you please suggest?
with kind regards
Rohit

**Comment by qingyun-wu** [comment]
Hi @itabhiyanta, 

Thank you for your question. When defining the custom metric, you need to manually configure the 11 arguments (even if you are not using them) required. For the ones you are not using, you can set the value to None. Please find a reference in this example: https://github.com/microsoft/FLAML/blob/16a97bec76ba101d62b1eb05484b20cc7c271e1c/test/test_automl.py#L128

**Comment by itabhiyanta** [comment]
Hi @qingyun-wu 

I tried according to the example but I got this error now.

-------------------------
```
[flaml.automl: 09-27 07:07:35] {1431} INFO - Evaluation method: holdout
[flaml.automl: 09-27 07:07:36] {1477} INFO - Minimizing error metric: customized metric
[flaml.automl: 09-27 07:07:36] {1514} INFO - List of ML learners in AutoML Run: ['lgbm', 'xgboost']
[flaml.automl: 09-27 07:07:36] {1746} INFO - iteration 0, current learner lgbm
Traceback (most recent call last):
  File "src/models/training/lgb_flaml.py", line 113, in <module>
    main()
  File "src/models/training/lgb_flaml.py", line 85, in main
    X_val=dataset_handler.x_test.to_numpy(), y_val=dataset_handler.test_set_output.to_numpy(), **settings)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/automl.py", line 1533, in fit
    self._search()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/automl.py", line 2020, in _search
    self._search_sequential()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/automl.py", line 1836, in _search_sequential
    use_ray=False,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/tune/tune.py", line 384, in run
    result = training_function(trial_to_run.config)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/automl.py", line 240, in _compute_with_config_base
    self.fit_kwargs,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/ml.py", line 445, in compute_estimator
    fit_kwargs=fit_kwargs,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/ml.py", line 278, in get_test_loss
    fit_kwargs,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/ml.py", line 239, in _eval_estimator
    return test_loss, metric_for_logging, pred_time, test_pred_y
UnboundLocalError: local variable 'pred_time' referenced before assignment
```

------------------------------------------------------------------------------------

I modified my code like this

`def custom_metric(X_test, y_test, estimator, labels, X_train, y_train, weight_test=None, weight_train=None,
                      config=None, groups_test=None, groups_train=None):
        outputs = estimator.predict(X_test)
        y_true = np.asarray(dataset_handler.test_set_output[
                                dataset_handler.cfg.label_column_name].tolist())
        y_pred = np.asarray(outputs)
        mape_error = round(
            np.mean(np.abs((y_true - y_pred) / y_true)) * 100, 3)
        print('Mape error (manually calculated is :', str(mape_error), file=log_file)
        return mape_error, estimator.get_params

    settings = {
        "time_budget": 3600,  # total running time in seconds
        "metric": custom_metric,  # primary metrics for regression can be chosen from: ['mae','mse','r2']
        "estimator_list": ['lgbm', 'xgboost'],  # list of ML learners; we tune lightgbm in this example
        "task": 'regression',  # task type
        "log_file_name": 'exp2_flaml_lgb_xgb_custom.log',  # flaml log file
        "seed": 7654321,  # random seed
    }
    '''The main flaml automl API'''
    automl.fit(X_train=dataset_handler.x_train.to_numpy(), y_train=dataset_handler.y_train.to_numpy(),
            X_val=dataset_handler.x_test.to_numpy(), y_val=dataset_handler.test_set_output.to_numpy(), **settings)
`

I got around that error by defining the missing variables like so

```
 test_pred_y=y_pred
 pred_time=0.0
 return mape_error, estimator.get_params, pred_time, test_pred_y
```
However then i got these errors

```
[flaml.automl: 09-27 07:16:49] {1431} INFO - Evaluation method: holdout
[flaml.automl: 09-27 07:16:50] {1477} INFO - Minimizing error metric: customized metric
[flaml.automl: 09-27 07:16:50] {1514} INFO - List of ML learners in AutoML Run: ['lgbm', 'xgboost']
[flaml.automl: 09-27 07:16:50] {1746} INFO - iteration 0, current learner lgbm
Traceback (most recent call last):
  File "src/models/training/lgb_flaml.py", line 115, in <module>
    main()
  File "src/models/training/lgb_flaml.py", line 87, in main
    X_val=dataset_handler.x_test.to_numpy(), y_val=dataset_handler.test_set_output.to_numpy(), **settings)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/automl.py", line 1533, in fit
    self._search()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/automl.py", line 2020, in _search
    self._search_sequential()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/automl.py", line 1836, in _search_sequential
    use_ray=False,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/tune/tune.py", line 384, in run
    result = training_function(trial_to_run.config)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/automl.py", line 240, in _compute_with_config_base
    self.fit_kwargs,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/ml.py", line 445, in compute_estimator
    fit_kwargs=fit_kwargs,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/ml.py", line 278, in get_test_loss
    fit_kwargs,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flaml/ml.py", line 233, in _eval_estimator
    fit_kwargs.get("groups"),
ValueError: too many values to unpack (expected 2)

```

I am wondering if missed something again.
Kindly advise.

**Comment by sonichi** [comment]
@itabhiyanta could you try version 0.6.5? If you don't need to log any additional metric, simply
`return mape_error, {}` in your custom metric function.
