### ISSUE TITLE
FLAML_sample_size cause train error

### ISSUE THREAD

**Issue by Tint0ri** [microsoft/FLAML#417]
try to make a classification task on 0.9.5 and 0.9.4. But always exit with this exception: 

[flaml.automl: 01-22 05:58:44] {2705} INFO - selected model: XGBClassifier(base_score=0.5, booster='gbtree',
              colsample_bylevel=0.04654671402865765, colsample_bynode=1,
              colsample_bytree=0.7848077464977525, gamma=0, gpu_id=-1,
              grow_policy='lossguide', importance_type='gain',
              interaction_constraints='', learning_rate=0.0011428762430722669,
              max_delta_step=0, max_depth=0, max_leaves=1213,
              min_child_weight=0.004718140051592224, missing=nan,
              monotone_constraints='()', n_estimators=2, n_jobs=-1,
              num_parallel_tree=1, objective='multi:softprob', random_state=0,
              reg_alpha=0.013005064769265464, reg_lambda=581.173515441408,
              scale_pos_weight=None, subsample=0.6150642735130163,
              tree_method='hist', use_label_encoder=False,
              validate_parameters=1, verbosity=0)
[flaml.automl: 01-22 05:58:44] {2739} INFO - [('xgboost', <flaml.model.XGBoostSklearnEstimator object at 0x7f19d8c5f490>), ('extra_tree', <flaml.model.ExtraTreesEstimator object at 0x7f19854695e0>), ('lgbm', <flaml.model.LGBMEstimator object at 0x7f1985469c70>), ('rf', <flaml.model.RandomForestEstimator object at 0x7f19854693a0>), ('catboost', <flaml.model.CatBoostEstimator object at 0x7f1981d54310>)]
[LightGBM] [Warning] Unknown parameter: FLAML_sample_size
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/sklearn/utils/fixes.py", line 211, in __call__
    return self.function(*args, **kwargs)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/sklearn/ensemble/_base.py", line 42, in _fit_single_estimator
    estimator.fit(X, y)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/flaml/model.py", line 968, in fit
    self._fit(X_train, y_train, **kwargs)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/flaml/model.py", line 151, in _fit
    model = self.estimator_class(**self.params)
TypeError: __init__() got an unexpected keyword argument 'FLAML_sample_size'
"""

The above exception was the direct cause of the following exception:

**Comment by sonichi** [comment]
I created a PR to fix this issue. If you'd like to share more about your use case or join the community, feel free to chat on [gitter](https://gitter.im/FLAMLer/community#).

**Comment by Tint0ri** [comment]
Thanks. Look forward to testing on new FLAML release.
